matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_US
  dictionary:
    encoding: utf-8
    wordlists:
    - .github/config/en-custom.txt
    - .github/config/en-drasi.txt
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.fenced_code
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  - pyspelling.filters.regex:
      patterns:
      - '\b\w+\.png\b'   # Exclude words ending with .png
  sources:
  - 'docs/content/**/*.md'
  default_encoding: utf-8